// MPLAN Magazine — home page grid + category filter

import { getArticles, SANITY_ENABLED, thumbUrl } from "./sanity-client.js";

const CATEGORIES = ["matter", "projects", "letters", "address", "notes"];

function toneClass(i) { return "y" + (((i * 3) % 7) + 1); }

function render(articles) {
  const grid = document.getElementById("grid");
  grid.innerHTML = "";
  const frag = document.createDocumentFragment();

  articles.forEach((a, i) => {
    // Build a hotspot-aware square thumbnail URL from the Sanity image
    // (respects the crop the editor set in the Studio). The LQIP is a
    // tiny base64 blob auto-generated by Sanity — used as an inline
    // blurred placeholder so the tile is never blank.
    const coverImg = a.coverImage?.asset || a.coverImage;
    const coverSrc = coverImg ? thumbUrl(coverImg, 600) : "";
    const lqip     = coverImg?.lqip || "";

    const el = document.createElement("a");
    el.className = "thumb " + toneClass(i);
    if (coverSrc) el.classList.add("has-image");
    el.href = `article.html?slug=${encodeURIComponent(a.slug)}`;
    el.dataset.cat = a.category;

    const tile = document.createElement("span");
    tile.className = "tile";
    // LQIP as the tile's background — shows instantly, zero network.
    if (lqip) tile.style.backgroundImage = `url("${lqip}")`;

    // High-res image overlays the LQIP and fades in once it's decoded.
    // `loading="lazy"` defers off-screen tiles automatically (native).
    if (coverSrc) {
      const img = document.createElement("img");
      img.loading = "lazy";
      img.decoding = "async";
      img.alt = "";
      img.addEventListener("load", () => img.classList.add("loaded"));
      img.src = coverSrc;
      // If the browser had it cached, `load` already fired before we
      // attached the listener — backfill via the complete flag.
      if (img.complete && img.naturalWidth > 0) img.classList.add("loaded");
      tile.appendChild(img);
    }

    el.appendChild(tile);

    const meta = document.createElement("span");
    meta.className = "meta";
    const title = document.createElement("span");
    title.className = "title";
    title.textContent = a.title;
    const author = document.createElement("span");
    author.className = "author";
    author.textContent = a.author;
    meta.appendChild(title);
    meta.appendChild(author);
    el.appendChild(meta);

    frag.appendChild(el);
  });

  grid.appendChild(frag);
}

function updateCounts(articles) {
  const counts = { all: articles.length };
  CATEGORIES.forEach(c => counts[c] = 0);
  articles.forEach(a => { if (counts[a.category] != null) counts[a.category]++; });
  document.querySelectorAll("sup[data-count]").forEach(sup => {
    const k = sup.dataset.count;
    sup.textContent = counts[k] != null ? counts[k] : 0;
  });
}

function bindFilter() {
  const cats = document.querySelectorAll(".categories .cat");
  cats.forEach(link => {
    link.addEventListener("click", (e) => {
      e.preventDefault();
      cats.forEach(c => c.classList.remove("active"));
      link.classList.add("active");
      const target = link.dataset.cat;
      document.querySelectorAll(".thumb").forEach(t => {
        const match = target === "all" || t.dataset.cat === target;
        t.classList.toggle("dimmed", !match);
      });
    });
  });

  // Inline intro links trigger category filter
  document.querySelectorAll(".intro a[data-cat]").forEach(a => {
    a.addEventListener("click", (e) => {
      e.preventDefault();
      const match = document.querySelector(`.categories .cat[data-cat="${a.dataset.cat}"]`);
      if (match) match.click();
      window.scrollTo({ top: 0, behavior: "smooth" });
    });
  });
}

// On touch devices, require two taps on a thumb:
//   1st tap → show hover-style overlay (blur + title/author) via `.tapped`
//   2nd tap on the same thumb → follow the link to the article
// Tapping a different thumb shifts focus; tapping elsewhere clears it.
function bindTouchHover() {
  if (!window.matchMedia("(hover: none)").matches) return;

  let active = null;
  document.querySelectorAll(".thumb").forEach(thumb => {
    thumb.addEventListener("click", (e) => {
      if (active !== thumb) {
        e.preventDefault();
        if (active) active.classList.remove("tapped");
        thumb.classList.add("tapped");
        active = thumb;
      }
      // else: second tap on the active thumb — allow navigation
    });
  });

  document.addEventListener("click", (e) => {
    if (active && !active.contains(e.target)) {
      active.classList.remove("tapped");
      active = null;
    }
  });
}

async function init() {
  let articles = [];
  if (SANITY_ENABLED) articles = await getArticles() || [];

  render(articles);
  updateCounts(articles);
  bindFilter();
  bindTouchHover();
}

document.addEventListener("DOMContentLoaded", init);
